### ISSUE TITLE
Attempting to visit air.mozilla.org causes redirection loop related to auth0

### ISSUE THREAD

**Issue by gene1wood** [mozilla/airmozilla#827]
When a user is sent by air.mozilla.org to the Auth0 `/authorize` endpoint and Auth0 finds that the user isn't logged in it's configured to redirect the user to this callback URL

```
https://air.mozilla.org/oidc/callback/?error=login_required&error_description=Login%20required&state=Bcb...
```

When air.mozilla.org gets a call to that callback URL, it then redirects the user to the URL

```
https://air.mozilla.org/login-failure/
```

Unfortunately, this URL is *also* protected by Auth0, which causes the user to be redirected to Auth0, and the loop begins again.

This loop occurs 7 times at which point the browser shows the error

```
The page isn’t redirecting properly
Firefox has detected that the server is redirecting the request for this address in a way that will never complete.
This problem can sometimes be caused by disabling or refusing to accept cookies.
```

Here is a HAR of the problem

[Archive 18-03-07 10-11-05.har.gz](https://github.com/mozilla/airmozilla/files/1790498/Archive.18-03-07.10-11-05.har.gz)

**Comment by peterbe** [comment]
https://air.mozilla.org/login-failure/ is not protected. Anybody can open it. 
```
▶ curl -I https://air.mozilla.org/login-failure/  | grep HTTP
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
HTTP/2 200
```
<img width="1560" alt="screen shot 2018-03-15 at 3 59 19 pm" src="https://user-images.githubusercontent.com/26739/37488197-42e9ff8e-286a-11e8-9c21-1890bf31af91.png">


I wonder if it's some session cookie that is hell bent on trying to re-login or something. 

Do you know, how can I fail to log in?
When I type in "pjdfpijwec@oicej4c.com" as the email I see this:
<img width="495" alt="screen shot 2018-03-15 at 4 01 57 pm" src="https://user-images.githubusercontent.com/26739/37488214-52e396fc-286a-11e8-90ee-b06b65043f6f.png">

**Comment by peterbe** [comment]
I suspect it's got nothing to do with the `/login-failure/` page but perhaps `mozilla-django-oidc` has a piece of middleware that, due to some session cookie, is intent on redirecting the user.

**Comment by peterbe** [comment]
Ah! I think we're suffering from this: https://github.com/mozilla/mozilla-django-oidc/issues/153

**Comment by peterbe** [comment]
@gene1wood The only thing that can really redirect you on a page like `/login-failure/` is the `RefreshIDToken` middleware. It's got nothing to do with what URL you're on since the middleware works for almost any URL (except some blacklisted ones). The RefreshIDToken does a redirect ONLY based on this list of conditions:

* GET request
* You're authenticated already
* It's not an AJAX request
* You're not on urls like `[u'/oidc/authenticate/', u'/oidc/callback/', u'/oidc/logout/']`
* you don't have a future session cookie for `oidc_id_token_expiration`

I have a feeling you actually *were* authenticated but the ID token refresh redirect dance was upset and sent you back to `/oidc/callback/?error=login_required&error_description=Login%20required&state=Bcb...`. That back, then redirected you to harmless little `/login-failure/`. And since you're still signed in, but not without a `oidc_id_token_expiration` session cookie, you are redirected to `https://auth.mozilla.auth0.com/authorize?nonce=mTeIPqMIGv3qGcI0vh5etSH0eNS4ojiv&prompt=none&state=KBT3WpufwH8N49a3t3JI0sDKPcIbz3EO&redirect_uri=https%3A%2F%2Fair.mozilla.org%2Foidc%2Fcallback%2F&response_type=code&client_id=nV1rnMMkB4uX9IewNOCitqy8NoyXVHlM&scope=openid+email` which rejects and spits you back to `/oidc/callback/?error=login_required&error_description=Login%20required&state=Bcb...` and the redirect madness starts all over again. 

One thing I don't understand is, if you *were* signed in, how did you even manage to get to the "Sign in" button (the one that redirects to to Auth0).

**Comment by peterbe** [comment]
Perhaps you didn't click the "Sign in" button to kick off the craziness. Perhaps you were merrily logged in and on your next click, the middleware decided it was time for you to refresh your ID token and that fails. 

Any idea how to reproduce that?

**Comment by gene1wood** [comment]
> One thing I don't understand is, if you were signed in, how did you even manage to get to the "Sign in" button (the one that redirects to to Auth0).

I don't remember. I suspect I clicked sign-in which took me to the sign-in button which I clicked, but I could be wrong.

> Any idea how to reproduce that?

The next time it happens to me I can gather more data. Is the thing missing from the `HAR` the step before the first step?

**Comment by peterbe** [comment]
I only know how to open a HAR file in Chrome's Network dev tools. It just shows the URLs that happened. I don't know how to play it. 

What makes things tricky is that you can't just go to `/oidc/callback/?error=login_required&error_description=Login%20required&state=Bcb...` because it's not reproducing the redirect loop.

**Comment by gene1wood** [comment]
I think I just have to wait till it happens again and capture more data. I imagine it will happen after the weekend as I won't be logged in for a couple days.

**Comment by peterbe** [comment]
I see it too now. As in, I can't get in myself.
The URL it redirects to is:
```
https://air.mozilla.org/oidc/callback/?error=login_required&error_description=Multifactor%20authentication%20required&state=wydDOdYzzJT....
```
**"Multifactor%20authentication%20required"**

I was logged in on Friday last week and I guess now Mozilla Auth0 wants me to do something extra, i.e. 2FA. 

I think the problem is that mozilla-django-oidc fails to log me out when the refresh redirect thing fails. I'll try to move this information over to the mozilla-django-oidc project.

**Comment by Phrozyn** [comment]
I was able to view airmo last week without issue, however today I tried and got the redirect loop. I had closed my browser friday evening but I'm thinking it didn't close completely. So I was thinking the cache should have been cleared upon trying to reach airmo today. 

After some poking around I realized Firefox needed a restart to update, so I restarted. 
Afterwards I was able to reach airmo just fine. My browser settings clear cache and history on restart.

**Comment by hotsphink** [comment]
I got the redirect loop. Then I logged in to check the mana page for #moco. Then I was able to get to air.mozilla.org as well.

**Comment by justindarc** [comment]
Went to `air.mozilla.org` and got this:
[Archive 18-03-19 12-38-02.har.zip](https://github.com/mozilla/airmozilla/files/1825914/Archive.18-03-19.12-38-02.har.zip)

**Comment by jensimmons** [comment]
I get the redirect loop in every copy of Firefox and Chrome. It's been slowly breaking one browser after another.

**Comment by pmac** [comment]
A workaround for now is to delete all "air.mozilla.org" cookies and login again.

**Comment by peterbe** [comment]
I **think** this solves the problem for mozilla-django-oidc. https://github.com/mozilla/mozilla-django-oidc/pull/213

However, for airmozilla the state of things are different. So perhaps instead of waiting for a new release of mozilla-django-oidc I just add a hasty extra middleware that does the same thing.

**Comment by peterbe** [comment]
Inbound upgrade to remedy this quickly: https://bugzilla.mozilla.org/show_bug.cgi?id=1447117

**Comment by peterbe** [comment]
@gene1wood 
Airmozilla isn't particular important but the quick fix I threw together is a rough version of a [change I'm proposing to mozilla-django-oidc](https://github.com/mozilla/mozilla-django-oidc/pull/213) and it's quite non-trivial but nevertheless important. 
Would you mind doing a test of this, using air.mozilla.org

1. Log in, close your browser session. 
2. Go to Auth0 admin and disable the relevant user
3. Open air.mozilla.org 
Expected result: Signed out
4. Enable the account again in Auth0 Admin
5. Go back to air.mozilla.org and you should be able to sign in again.

**Comment by gene1wood** [comment]
Sure.

1. I started a new browser session, went to air.mozilla.org clicked sign in was taken to Auth0 and signed in with my LDAP
2. I confirmed I was now logged into air.mozilla.org
3. I closed my browser
4. I blocked my production user in Auth0
5. I opened my browser and went to air.mozilla.org
6. I was still logged into air.mozilla.org

This is what I would expect though. Blocking a user in Auth0 wouldn't have any affect on an RPs session for that user.

**Comment by peterbe** [comment]
> This is what I would expect though. Blocking a user in Auth0 wouldn't have any affect on an RPs session for that user.

No it should have an affect. In Django we set a cookie that lasts a *long* time but there's a piece of middleware periodically forces you to go to Auth0 again (with that `prompt=none`). That should happen to you too and it should fail and when you *come back* to air.mozilla.org you should now be logged out. I suspect that [the little timer](https://github.com/mozilla/mozilla-django-oidc/blob/5916a69ed7870053c4d4e194b45b42c2fac49496/mozilla_django_oidc/middleware.py#L92) that knows when it's time to refresh the session didn't kick in in your case. Perhaps if you click around a little bit longer.
